### ISSUE TITLE
Roap map for openldap 2.4.x series

### ISSUE THREAD

**Issue by manavchouhan115** [openldap/openldap.github.io#2]
What is the roadmap for openldap 2.4.x series? As 2.5.x and 2.6.x series are available now, will the support for 2.4.x will be removed? Can someone please provide any information regarding End of life of this series.

**Comment by mueddib** [comment]
Hello, I think you made your request in a different place. Still, I would love to tell you about OpenLDAP.

OpenLDAP is currently up-to-date with version 2.6.0. However, support for the 2.4 series still continues. However, we invite you to update to the new version. Because you should see major changes.

> What is the roadmap for openldap 2.4.x series? As 2.5.x and 2.6.x series are available now, will the support for 2.4.x will be removed? Can someone please provide any information regarding End of life of this series.

Hello, i think you made issue request in a different place so still i would like to tell you about OpenLDAP. OpenLDAP is currently up-to-date with version v2.6.0 however OpenLDAP Team support for v2.4 series still continues but invite you to update to new version and read Release Announcement and check major changes.

https://www.openldap.org/software/release/announce.html

**Comment by quanah** [comment]
The correct location to ask this information is on the openldap-technical@openldap.org list.  However, I suggest reading the archives of the openldap-announce list as the release policy was recently posted there.  I'd also suggest subscribing to that list in addition to -technical if you are an openldap user.  OpenLDAP 2.4 is no longer supported.
